/* Build 1 - Gabinet Neurologopedyczny
   Single application script. All appointment/date logic lives here.
   Database timestamps are UTC; user-entered/displayed times are Europe/Warsaw.
*/

const SUPABASE_URL='https://dclbsucsccsegvpmmgdn.supabase.co';
const SUPABASE_ANON='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjbGJzdWNzY3NlZ2d2bW1tZ2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwOTA1NjksImV4cCI6MjEwMjY2NjU2OX0.HEVj0gPxioLmCR8SZYgt8qi-Nw47UMYrSgKLUrBZedQ';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON);
const TZ='Europe/Warsaw';
const THERAPIST_EMAILS=['kontakt@logopedaostroda.pl','ziomekzpolski@yahoo.com'];
const MONTH_LABELS=['Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'];
const RESCHED_REGEX=/ \[(Prośba o przełożenie na|Propozycja logopedy:) .+\]$/;
let currentUser=null,isTherapist=false,currentProfile=null,calendar=null,allPatients=[],selectedAptPatient=null,selectedAccountPatient=null,allExercises=[],exerciseFavIds=[],allNotifications=[],notifFilter='unread';

const pad=n=>String(n).padStart(2,'0');
function partsInWarsaw(iso){const d=new Date(iso);const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(d).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]));return p;}
function warsawLocalToISO(date,time){const [y,m,d]=date.split('-').map(Number),[h,min]=time.split(':').map(Number);const target=Date.UTC(y,m-1,d,h,min,0);const fmt=new Intl.DateTimeFormat('en-GB',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});for(let off=-14;off<=14;off++){const x=new Date(target-off*3600000),p=Object.fromEntries(fmt.formatToParts(x).filter(a=>a.type!=='literal').map(a=>[a.type,Number(a.value)]));if(p.year===y&&p.month===m&&p.day===d&&p.hour===h&&p.minute===min&&p.second===0)return x.toISOString();}throw new Error('Nieprawidłowa data/godzina dla Europe/Warsaw.');}
function warsawDateTime(iso){return new Intl.DateTimeFormat('pl-PL',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso));}
function warsawTime(iso){return new Intl.DateTimeFormat('pl-PL',{timeZone:TZ,hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso));}
function warsawDate(iso){return new Intl.DateTimeFormat('pl-PL',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(iso));}
function polandDateTimeToISO(date,time){return warsawLocalToISO(date,time);}
function isoToLocalParts(iso){const p=partsInWarsaw(iso);return {date:`${p.year}-${pad(p.month)}-${pad(p.day)}`,time:`${pad(p.hour)}:${pad(p.minute)}`};}

function appointmentTitle(a){return stripRescheduleRequest(a?.title||'')||'Wizyta logopedyczna';}
function stripRescheduleRequest(title){return(title||'').replace(RESCHED_REGEX,'').trim();}
function extractRescheduleInfo(a){const m=(a?.title||'').match(RESCHED_REGEX);if(!m)return null;const s=m[0];if(s.includes('Prośba o przełożenie na'))return{role:'patient',proposedDate:s.replace(' [Prośba o przełożenie na ','').replace(']','')};if(s.includes('Propozycja logopedy:'))return{role:'therapist',proposedDate:s.replace(' [Propozycja logopedy: ','').replace(']','')};return null;}
function extractRescheduleRequest(a){const i=extractRescheduleInfo(a);return i?i.proposedDate:null;}
function statusLabel(s){return{scheduled:'Zaplanowana',pending:'Oczekująca',confirmed:'Potwierdzona',cancelled:'Anulowana',reschedule_requested:'Prośba o przełożenie',reschedule_proposed:'Propozycja logopedy'}[s]||s;}
function recurringLabel(t){return{weekly:'Co tydzień',biweekly:'Co 2 tygodnie',monthly:'Co miesiąc'}[t]||t;}

async function dbUpdate(table,values,filters){let q=sb.from(table).update(values);for(const [k,v] of Object.entries(filters||{}))q=q.eq(k,v);const r=await q; if(r.error)throw r.error;return r;}
async function dbInsert(table,rows){const r=await sb.from(table).insert(rows);if(r.error)throw r.error;return r;}
async function dbSelectOne(table,select,id){const r=await sb.from(table).select(select).eq('id',id).single();if(r.error)throw r.error;return r.data;}
async function isSlotTaken(date,time,excludeId=''){const iso=warsawLocalToISO(date,time);let q=sb.from('appointments').select('id').eq('appointment_date',iso).neq('status','cancelled').limit(1);if(excludeId)q=q.neq('id',excludeId);const r=await q;if(r.error)throw r.error;return !!r.data?.length;}

function generateRecurringAppointments(startDate,startTime,type,months){const [y,m,d]=startDate.split('-').map(Number),selected=new Set((months||[]).map(Number)),out=[];if(!selected.size)return out;if(type==='monthly'){for(const mo of [...selected].sort((a,b)=>a-b)){if(mo<1||mo>12)continue;const last=new Date(Date.UTC(y,mo,0)).getUTCDate(),day=Math.min(d,last),date=`${y}-${pad(mo)}-${pad(day)}`;if(date>startDate)out.push({date,time:startTime});}return out;}const step=type==='biweekly'?14:7,cursor=new Date(Date.UTC(y,m-1,d));const end=new Date(Date.UTC(y,11,31));while(true){cursor.setUTCDate(cursor.getUTCDate()+step);if(cursor>end)break;const cm=cursor.getUTCMonth()+1;if(selected.has(cm))out.push({date:`${cursor.getUTCFullYear()}-${pad(cm)}-${pad(cursor.getUTCDate())}`,time:startTime});}return out;}

async function init(){const raw=localStorage.getItem('sb-session');let session=null;try{session=JSON.parse(raw||'null')}catch{}if(!session?.access_token){location.href='login.html';return;}const auth=await sb.auth.getUser(session.access_token);if(auth.error||!auth.data?.user){localStorage.removeItem('sb-session');location.href='login.html';return;}currentUser=auth.data.user;const p=await sb.from('profiles').select('*').eq('id',currentUser.id).maybeSingle();if(p.error){showToast('Nie udało się pobrać profilu: '+p.error.message,'error');return;}currentProfile=p.data;if(!currentProfile){const role=THERAPIST_EMAILS.includes(currentUser.email)?'therapist':'patient';const r=await sb.from('profiles').upsert({id:currentUser.id,email:currentUser.email,role},{onConflict:'id'}).select().single();if(r.error){showToast('Błąd tworzenia profilu: '+r.error.message,'error');return;}currentProfile=r.data;}isTherapist=THERAPIST_EMAILS.includes(currentUser.email)||currentProfile.role==='therapist';document.getElementById('nav-greeting').textContent=`Cześć ${currentUser.email}!`;buildNavTabs();initCalendar();initRecurringMonths('recurring-months');bindEvents();await Promise.all([loadExercises(),loadNotifications(),loadProfile(),isTherapist?loadPatients():Promise.resolve()]);await checkAutoCancellation();setInterval(checkAutoCancellation,5*60*1000);try{sb.channel('notif-changes').onPostgresChanges({event:'*',schema:'public',table:'notifications'},loadNotifications).subscribe()}catch(e){console.warn('Realtime notifications unavailable',e)}}
document.addEventListener('DOMContentLoaded',init);

function bindEvents(){const id=x=>document.getElementById(x);id('logout-btn').onclick=logout;id('new-appointment-btn').onclick=()=>openNewAptModal();id('add-exercise-btn').onclick=()=>openModal('exercise-modal');id('create-profile-btn').onclick=()=>openNewProfileInAccounts();id('mark-all-read').onclick=markAllRead;id('account-search').addEventListener('input',e=>renderAccountList(e.target.value));id('apt-patient-search').addEventListener('input',e=>filterCombobox(e.target.value,'apt-patient-dropdown',selectAptPatient));id('apt-patient-search').addEventListener('focus',e=>filterCombobox(e.target.value,'apt-patient-dropdown',selectAptPatient));id('apt-recurring').addEventListener('change',e=>id('recurring-options').classList.toggle('hidden',!e.target.checked));id('profile-form').addEventListener('submit',saveProfile);id('prof-dob').addEventListener('change',()=>calcAgeField('prof-dob','prof-age'));id('account-edit-form').addEventListener('submit',saveAccountPatient);id('acc-dob').addEventListener('change',()=>calcAgeField('acc-dob','acc-age'));id('new-appointment-form').addEventListener('submit',createAppointment);id('exercise-form').addEventListener('submit',saveExercise);id('apt-date').addEventListener('change',initAptTimeSelect);id('resched-date').addEventListener('change',()=>{const b=document.getElementById('resched-confirm');if(b.dataset.aptId)loadReschedSlots(b.dataset.aptId)});document.querySelectorAll('.modal-close,.modal-overlay,.modal-close-btn').forEach(e=>e.addEventListener('click',closeModalAll));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModalAll()});}

function buildNavTabs(){const c=document.getElementById('nav-tabs-container');c.innerHTML='';const tabs=[['calendar','📅','Kalendarz'],['exercises','🏋️','Ćwiczenia'],['accounts','👥','Konta'],['profile','👤','Profil'],['notifications','🔔','Powiadomienia'],['contact','📞','Kontakt']];tabs.forEach(([id,emoji,label])=>{if(id==='accounts'&&!isTherapist||id==='profile'&&isTherapist)return;const b=document.createElement('button');b.className='nav-tab';b.dataset.tab=id;b.innerHTML=`${emoji} ${label}${id==='notifications'?'<span class="notif-badge hidden" id="notif-badge">0</span>':''}`;b.onclick=()=>switchTab(id);c.appendChild(b)});if(isTherapist){document.getElementById('new-appointment-btn').classList.remove('hidden');document.getElementById('exercise-therapist-controls').classList.remove('hidden');}}
function switchTab(id){document.querySelectorAll('.tab-panel').forEach(p=>p.classList.remove('active'));document.getElementById('tab-'+id)?.classList.add('active');document.querySelectorAll('.nav-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));if(id==='calendar')calendar?.updateSize();if(id==='accounts')renderAccountList(document.getElementById('account-search').value);document.getElementById('broadcast-btn-container')?.classList.toggle('hidden',!isTherapist);}

function initCalendar(){const el=document.getElementById('calendar');if(!el)return;calendar?.destroy?.();calendar=new FullCalendar.Calendar(el,{locale:'pl',timeZone:TZ,initialView:'dayGridMonth',headerToolbar:{left:'dayGridMonth,timeGridWeek,timeGridDay',center:'title',right:'prev,today,next'},buttonText:{month:'Miesiąc',week:'Tydzień',day:'Dzień',today:'Dziś'},slotMinTime:'07:00:00',slotMaxTime:'21:00:00',slotDuration:'01:00:00',allDaySlot:false,height:'auto',displayEventTime:true,eventTimeFormat:{hour:'2-digit',minute:'2-digit',hour12:false},events:fetchCalendarEvents,eventClick:handleEventClick,dateClick:isTherapist?handleDateClick:undefined});calendar.render();}
async function fetchCalendarEvents(info,success,fail){try{await checkAutoCancellation();const from=info.startStr.slice(0,10),to=info.endStr.slice(0,10);let q=sb.from('appointments').select('id,title,appointment_date,status,recurring_type,recurring_parent,patient_email,patient_name,patient_phone,patient_dob').gte('appointment_date',warsawLocalToISO(from,'00:00')).lt('appointment_date',warsawLocalToISO(to,'00:00')).neq('status','cancelled');if(!isTherapist)q=q.eq('patient_email',currentUser.email);const r=await q;if(r.error)throw r.error;success((r.data||[]).map(a=>({id:a.id,title:isTherapist?a.title:'Wizyta logopedyczna',start:a.appointment_date,backgroundColor:a.status==='confirmed'?'#22c55e':a.status==='reschedule_requested'?'#f97316':a.status==='reschedule_proposed'?'#d97706':'#3b82f6',extendedProps:a})));}catch(e){console.error(e);fail(e)}}
function handleEventClick(info){showAptDetail(info.event.extendedProps)}
function handleDateClick(info){if(isTherapist)openNewAptModal(info.dateStr)}

function showAptDetail(a){const age=calcAge(a.patient_dob),ageStr=age===null?'':` (${age} lat)`,dt=isoToLocalParts(a.appointment_date),info=extractRescheduleInfo(a),body=document.getElementById('modal-body');let html=`<div class="detail-row"><strong>Pacjent:</strong> ${esc(a.patient_name||'')}${ageStr}</div><div class="detail-row"><strong>Data:</strong> ${esc(warsawDate(a.appointment_date))}</div><div class="detail-row"><strong>Godzina:</strong> ${esc(dt.time)}</div><div class="detail-row"><strong>Status:</strong> ${statusLabel(a.status)}</div>${a.patient_email?`<div class="detail-row"><strong>E-mail:</strong> ${esc(a.patient_email)}</div>`:''}${a.patient_phone?`<div class="detail-row"><strong>Telefon:</strong> ${esc(a.patient_phone)}</div>`:''}${a.recurring_parent||a.recurring_type?`<div class="detail-row"><strong>Cykliczność:</strong> ${recurringLabel(a.recurring_type||'weekly')}</div>`:''}`;if(info)html+=`<div class="negotiation-info"><strong>🔄 Negocjacja terminu</strong><br>${info.role==='patient'?'Pacjent':'Logopeda'} proponuje: <strong>${esc(info.proposedDate)}</strong><br><span style="font-size:.8rem;color:#92400e">Oczekuje na odpowiedź ${info.role==='patient'?'logopedy':'pacjenta'}</span></div>`;body.innerHTML=html;const actions=document.getElementById('modal-actions');actions.innerHTML='';if(a.status!=='cancelled')actions.innerHTML+=`<button class="btn btn-danger btn-sm" onclick="cancelAppointment('${a.id}')">Odwołaj wizytę</button> `;if(a.status==='reschedule_requested'&&isTherapist){actions.innerHTML+=`<button class="btn btn-primary btn-sm" onclick="acceptReschedule('${a.id}')">Akceptuj proponowany termin</button> <button class="btn btn-outline btn-sm" onclick="proposeAlternativeDate('${a.id}','therapist')">Zaproponuj inny termin</button>`}else if(a.status==='reschedule_proposed'&&!isTherapist){actions.innerHTML+=`<button class="btn btn-primary btn-sm" onclick="acceptReschedule('${a.id}')">Akceptuj proponowany termin</button> <button class="btn btn-outline btn-sm" onclick="proposeAlternativeDate('${a.id}','patient')">Zaproponuj inny termin</button>`}else if(isTherapist&&a.status!=='cancelled')actions.innerHTML+=`<button class="btn btn-outline btn-sm" onclick="openReschedule('${a.id}')">Przełóż wizytę</button>`;else if(!isTherapist&&a.status==='confirmed')actions.innerHTML+=`<button class="btn btn-outline btn-sm" onclick="requestReschedule('${a.id}')">Poproś o przełożenie</button>`;actions.innerHTML+=`<button class="btn btn-outline btn-sm" onclick="closeModalAll()">Wróć</button>`;document.getElementById('modal-title').textContent=appointmentTitle(a);openModal('appointment-modal');}

function initAptTimeSelect(){const s=document.getElementById('apt-time');if(!s)return;const old=s.value;s.innerHTML='';for(let h=7;h<=21;h++){const v=`${pad(h)}:00`,o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o)}s.value=[...s.options].some(o=>o.value===old)?old:'09:00';if(document.getElementById('apt-date').value)refreshAppointmentSlots();}
async function refreshAppointmentSlots(){const date=document.getElementById('apt-date').value;if(!date)return;const s=document.getElementById('apt-time');for(const o of s.options)o.disabled=false;try{const r=await sb.from('appointments').select('appointment_date').gte('appointment_date',warsawLocalToISO(date,'00:00')).lt('appointment_date',warsawLocalToISO(date,'23:59')).neq('status','cancelled');if(r.error)throw r.error;const taken=new Set((r.data||[]).map(a=>warsawTime(a.appointment_date)));for(const o of s.options)if(taken.has(o.value))o.disabled=true;}catch(e){showToast('Nie udało się sprawdzić dostępności: '+e.message,'error')}}
function initRecurringMonths(id){const g=document.getElementById(id);if(!g)return;g.innerHTML=MONTH_LABELS.map((m,i)=>`<button type="button" class="month-btn" data-month="${i+1}">${m.slice(0,3)}</button>`).join('');g.querySelectorAll('.month-btn').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));}
function getSelectedMonths(id){return[...document.getElementById(id).querySelectorAll('.month-btn.selected')].map(b=>Number(b.dataset.month));}
function openNewAptModal(dateStr=''){selectedAptPatient=null;document.getElementById('apt-patient-search').value='';document.getElementById('apt-patient-dropdown').classList.add('hidden');document.getElementById('apt-patient-data').classList.add('hidden');document.getElementById('apt-title').value='Wizyta logopedyczna';document.getElementById('apt-date').value=dateStr;document.getElementById('apt-recurring').checked=false;document.getElementById('recurring-options').classList.add('hidden');document.getElementById('apt-recurring-type').value='weekly';document.querySelectorAll('#recurring-months .month-btn').forEach(b=>b.classList.remove('selected'));initAptTimeSelect();openModal('new-appointment-modal');}
async function createAppointment(e){e.preventDefault();if(!isTherapist){showToast('Tylko logopeda może tworzyć wizyty.','error');return}if(!selectedAptPatient){showToast('Wybierz pacjenta z listy','error');return}const date=document.getElementById('apt-date').value,time=document.getElementById('apt-time').value,title=document.getElementById('apt-title').value.trim()||'Wizyta logopedyczna',rec=document.getElementById('apt-recurring').checked,type=rec?document.getElementById('apt-recurring-type').value:null,months=rec?getSelectedMonths('recurring-months'):[];if(!date||!time){showToast('Podaj datę i godzinę','error');return}if(rec&&!months.length){showToast('Wybierz co najmniej jeden miesiąc dla wizyt cyklicznych.','error');return}try{if(await isSlotTaken(date,time)){showToast('Ten termin jest już zajęty.','error');return}const patient={patient_email:selectedAptPatient.email,patient_name:`${selectedAptPatient.first_name||''} ${selectedAptPatient.last_name||''}`.trim(),patient_phone:selectedAptPatient.phone||'',patient_dob:selectedAptPatient.dob||null};const r=await sb.from('appointments').insert({...patient,appointment_date:warsawLocalToISO(date,time),title,status:'confirmed',recurring_type:type||'weekly'}).select().single();if(r.error)throw r.error;const main=r.data;if(rec){const rows=[];for(const a of generateRecurringAppointments(date,time,type,months)){if(!(await isSlotTaken(a.date,a.time)))rows.push({...patient,appointment_date:warsawLocalToISO(a.date,a.time),title,status:'pending',recurring_type:type,recurring_parent:main.id});}if(rows.length){const ir=await sb.from('appointments').insert(rows);if(ir.error)throw ir.error;}}calendar?.refetchEvents();closeModalAll();showToast('Wizyta utworzona');}catch(e){console.error(e);showToast('Błąd tworzenia wizyty: '+e.message,'error')}}

function openReschedule(aptId){openReschedulePicker(aptId,'therapist','Przełóż wizytę','Przełóż wizytę');}
function requestReschedule(aptId){openReschedulePicker(aptId,'patient','Poproś o przełożenie wizyty','Wyślij prośbę o przełożenie');}
function proposeAlternativeDate(aptId,role,notifId=''){openReschedulePicker(aptId,role==='therapist'?'therapist_counter':'patient_counter','Zaproponuj inny termin','Zaproponuj inny termin',notifId);}
function openReschedulePicker(aptId,mode,heading,button,notifId=''){closeModalAll();const b=document.getElementById('resched-confirm');b.dataset.aptId=aptId;b.dataset.mode=mode;b.dataset.notifId=notifId;b.dataset.time='';b.disabled=true;b.textContent=button;document.getElementById('resched-date').value='';document.getElementById('resched-slots').innerHTML='';document.querySelector('#reschedule-modal h3').textContent=heading;openModal('reschedule-modal');}
async function loadReschedSlots(aptId){const date=document.getElementById('resched-date').value,grid=document.getElementById('resched-slots');if(!date)return;try{const r=await sb.from('appointments').select('id,appointment_date').gte('appointment_date',warsawLocalToISO(date,'00:00')).lt('appointment_date',warsawLocalToISO(date,'23:59')).neq('status','cancelled').neq('id',aptId);if(r.error)throw r.error;const taken=new Set((r.data||[]).map(a=>warsawTime(a.appointment_date)));grid.innerHTML='';for(let h=7;h<=21;h++){const t=`${pad(h)}:00`,busy=taken.has(t),b=document.createElement('button');b.type='button';b.className='slot-btn'+(busy?' taken':'');b.textContent=busy?`${t} — Zajęte`:`${t} — Dostępne`;b.disabled=busy;if(!busy)b.onclick=()=>{grid.querySelectorAll('.slot-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const c=document.getElementById('resched-confirm');c.dataset.time=t;c.disabled=false};grid.appendChild(b)}}catch(e){console.error(e);grid.innerHTML='<div class="empty-msg">Nie udało się sprawdzić dostępności.</div>'}}
document.getElementById('resched-confirm')?.addEventListener('click',submitReschedule);
async function submitReschedule(){const b=document.getElementById('resched-confirm'),id=b.dataset.aptId,mode=b.dataset.mode,date=document.getElementById('resched-date').value,time=b.dataset.time,notifId=b.dataset.notifId||'';if(!id||!date||!time)return;try{if(await isSlotTaken(date,time,id)){showToast('Ten termin został właśnie zajęty.','error');await loadReschedSlots(id);return}const a=await dbSelectOne('appointments','id,title,patient_email,patient_name,appointment_date,status',id);if(!['confirmed','reschedule_requested','reschedule_proposed'].includes(a.status)){showToast('Ta wizyta nie jest już dostępna do przełożenia.','error');return}const proposed=`${date} ${time}`,orig=isoToLocalParts(a.appointment_date);let newStatus,newTitle;if(mode==='patient'||mode==='patient_counter'){newStatus='reschedule_requested';newTitle=`${appointmentTitle(a)} [Prośba o przełożenie na ${proposed}]`;if(a.status!=='reschedule_proposed'&&a.status!=='confirmed'){showToast('Nie można teraz wysłać tej prośby.','error');return}}else if(mode==='therapist_counter'){newStatus='reschedule_proposed';newTitle=`${appointmentTitle(a)} [Propozycja logopedy: ${proposed}]`;if(a.status!=='reschedule_requested'){showToast('Nie można teraz wysłać kontrpropozycji.','error');return}}else{newStatus='confirmed';newTitle=appointmentTitle(a);}const update={status:newStatus,title:newTitle};if(mode==='therapist')update.appointment_date=warsawLocalToISO(date,time);await dbUpdate('appointments',update,{id,status:a.status});if(mode==='patient'||mode==='patient_counter')await dbInsert('notifications',{patient_email:THERAPIST_EMAILS[0],message:`Pacjent ${a.patient_name||''} prosi o przełożenie wizyty z {{black:${orig.date} ${orig.time}}} na {{green:${proposed}}}`,type:'reschedule_therapist:'+id,is_read:false});else if(mode==='therapist_counter')await dbInsert('notifications',{patient_email:a.patient_email,message:`Logopeda proponuje nowy termin wizyty z {{black:${orig.date} ${orig.time}}} na {{green:${proposed}}}`,type:'reschedule_patient:'+id,is_read:false});else await dbInsert('notifications',{patient_email:a.patient_email,message:`Logopeda przełożył Twoją wizytę na ${proposed}`,type:'info',is_read:false});if(notifId)await dbUpdate('notifications',{is_read:true},{id:notifId});calendar?.refetchEvents();await loadNotifications();closeModalAll();showToast(mode==='therapist'?`Wizyta przełożona na ${proposed}`:'Propozycja wysłana: '+proposed);}catch(e){console.error(e);showToast('Błąd: '+e.message,'error')}}
async function acceptReschedule(aptId,notifId=''){try{const a=await dbSelectOne('appointments','id,title,patient_email,patient_name,appointment_date,status',aptId);const info=extractRescheduleInfo(a);if(!info){showToast('Brak aktywnej propozycji.','error');return}if(isTherapist&&info.role!=='patient'||!isTherapist&&info.role!=='therapist'){showToast('Nie możesz zaakceptować tej propozycji.','error');return}const [date,time]=info.proposedDate.split(' ');if(await isSlotTaken(date,time,aptId)){showToast('Proponowany termin jest już zajęty.','error');return}const expected=info.role==='patient'?'reschedule_requested':'reschedule_proposed';const u=await sb.from('appointments').update({appointment_date:warsawLocalToISO(date,time),status:'confirmed',title:appointmentTitle(a)}).eq('id',aptId).eq('status',expected);if(u.error)throw u.error;const fresh=await sb.from('appointments').select('id').eq('id',aptId).single();if(fresh.error||!fresh.data){showToast('Wizyta zmieniła się równocześnie. Spróbuj ponownie.','error');return}await dbInsert('notifications',{patient_email:info.role==='patient'?a.patient_email:THERAPIST_EMAILS[0],message:info.role==='patient'?`Logopeda zaakceptował Twój proponowany termin: ${info.proposedDate}. Wizyta potwierdzona!`:`Pacjent ${a.patient_name||''} zaakceptował proponowany termin: ${info.proposedDate}`,type:info.role==='patient'?'accepted_patient':'accepted_therapist',is_read:false});const n=await sb.from('notifications').select('id').like('type','reschedule_%:'+aptId);if(n.data?.length)await sb.from('notifications').update({is_read:true}).in('id',n.data.map(x=>x.id));if(notifId)await dbUpdate('notifications',{is_read:true},{id:notifId});calendar?.refetchEvents();await loadNotifications();closeModalAll();showToast('Termin potwierdzony: '+info.proposedDate);}catch(e){console.error(e);showToast('Błąd akceptacji: '+e.message,'error')}}

async function checkAutoCancellation(){try{const now=Date.now(),cutoff=now+24*60*60*1000,r=await sb.from('appointments').select('id,title,patient_email,patient_name,appointment_date,status').in('status',['reschedule_requested','reschedule_proposed']);if(r.error)throw r.error;for(const a of r.data||[]){const t=Date.parse(a.appointment_date);if(Number.isFinite(t)&&t>now&&t<=cutoff){const u=await sb.from('appointments').update({status:'cancelled',title:appointmentTitle(a)}).eq('id',a.id).in('status',['reschedule_requested','reschedule_proposed']);if(u.error)throw u.error;await dbInsert('notifications',[{patient_email:a.patient_email,message:'Wizyta została automatycznie anulowana – nie ustalono nowego terminu w ciągu 24h przed planowaną wizytą.',type:'cancel',is_read:false},{patient_email:THERAPIST_EMAILS[0],message:`Wizyta pacjenta ${a.patient_name||''} została automatycznie anulowana – brak ustalonego terminu (24h przed wizytą).`,type:'cancel',is_read:false}]);const n=await sb.from('notifications').select('id').like('type','reschedule_%:'+a.id);if(n.data?.length)await sb.from('notifications').update({is_read:true}).in('id',n.data.map(x=>x.id));}}}catch(e){console.error('Auto-cancellation:',e)}}

async function cancelAppointment(id){try{const a=await dbSelectOne('appointments','id,recurring_parent,recurring_type,patient_email,patient_name,title,status',id);if(a.status==='cancelled'){showToast('Wizyta jest już anulowana.','info');return}const root=a.recurring_parent||a.id;const children=await sb.from('appointments').select('id').eq('recurring_parent',root).limit(1);if(children.error)throw children.error;if(a.recurring_parent||children.data?.length){showSeriesCancelDialog(a,root);return}await cancelSingleAppointment(a);}catch(e){console.error(e);showToast('Błąd: '+e.message,'error')}}
function showSeriesCancelDialog(a,root){const old=document.getElementById('series-cancel-popup');old?.remove();const m=document.createElement('div');m.id='series-cancel-popup';m.className='modal';m.style.display='flex';const c=document.createElement('div');c.className='modal-content';c.innerHTML=`<h3>Wizyta cykliczna</h3><p>Ta wizyta należy do serii cyklicznej. Co chcesz zrobić?</p><div class="modal-footer"><button id="series-one" class="btn btn-outline btn-sm">Odwołaj tylko tę wizytę</button><button id="series-all" class="btn btn-danger btn-sm">Odwołaj całą serię</button><button id="series-back" class="btn btn-outline btn-sm">Wróć</button></div>`;m.appendChild(c);document.body.appendChild(m);document.getElementById('series-one').onclick=()=>{m.remove();cancelSingleAppointment(a)};document.getElementById('series-all').onclick=async()=>{if(!confirm('Na pewno odwołać WSZYSTKIE wizyty z tej serii? Tej operacji nie można cofnąć.'))return;m.remove();await cancelAppointmentSeries(a,root)};document.getElementById('series-back').onclick=()=>m.remove();}
async function cancelSingleAppointment(a){if(!confirm('Na pewno odwołać tę wizytę?'))return;const u=await sb.from('appointments').update({status:'cancelled',title:appointmentTitle(a)}).eq('id',a.id).neq('status','cancelled');if(u.error)throw u.error;await notifyCancellation(a,false);await markRescheduleNotificationsRead(a.id);calendar?.refetchEvents();await loadNotifications();closeModalAll();showToast('Wizyta anulowana');}
async function cancelAppointmentSeries(a,root){const r=await sb.from('appointments').select('id,patient_email,patient_name,title').or(`id.eq.${root},recurring_parent.eq.${root}`).neq('status','cancelled');if(r.error)throw r.error;const ids=(r.data||[]).map(x=>x.id);if(!ids.length){showToast('Seria jest już anulowana.','info');return}const u=await sb.from('appointments').update({status:'cancelled'}).in('id',ids).neq('status','cancelled');if(u.error)throw u.error;await notifyCancellation(a,true);for(const id of ids)await markRescheduleNotificationsRead(id);calendar?.refetchEvents();await loadNotifications();closeModalAll();showToast(`Anulowano ${ids.length} wizyt z serii.`);}
async function notifyCancellation(a,all){if(isTherapist&&a.patient_email)await dbInsert('notifications',{patient_email:a.patient_email,message:all?'Cała seria cyklicznych wizyt została odwołana przez logopedę.':'Wizyta została odwołana przez logopedę.',type:'cancel',is_read:false});else if(!isTherapist)await dbInsert('notifications',{patient_email:THERAPIST_EMAILS[0],message:all?`Pacjent ${a.patient_name||''} odwołał całą serię wizyt.`:`Pacjent ${a.patient_name||''} odwołał wizytę.`,type:'cancel',is_read:false});}
async function markRescheduleNotificationsRead(id){const r=await sb.from('notifications').select('id').like('type','reschedule_%:'+id);if(r.error)throw r.error;if(r.data?.length){const u=await sb.from('notifications').update({is_read:true}).in('id',r.data.map(x=>x.id));if(u.error)throw u.error}}

async function loadPatients(){const r=await sb.from('profiles').select('*').eq('role','patient').order('last_name');if(r.error){showToast('Błąd ładowania pacjentów: '+r.error.message,'error');return}allPatients=(r.data||[]).filter(p=>p.id!==currentUser.id&&p.email!==currentUser.email);renderAccountList('');}
function renderAccountList(query=''){const c=document.getElementById('account-list');if(!c)return;const q=(query||'').toLowerCase(),list=allPatients.filter(p=>!q||(p.first_name||'').toLowerCase().includes(q)||(p.last_name||'').toLowerCase().includes(q)||(p.email||'').toLowerCase().includes(q));c.innerHTML=list.length?list.map(p=>`<div class="account-list-item" data-id="${esc(p.id)}"><div class="account-list-info"><span class="account-list-name">${esc(p.last_name||'')} ${esc(p.first_name||'')}</span><span class="account-list-email">${esc(p.email||'')}</span></div><span class="account-list-arrow">›</span></div>`).join(''):'<div class="account-list-empty">Brak wyników</div>';c.querySelectorAll('.account-list-item').forEach(e=>e.onclick=()=>{const p=allPatients.find(x=>x.id===e.dataset.id);if(p)selectAccountPatient(p)});}
function filterCombobox(query,id,onSelect){const dd=document.getElementById(id);if(!query){dd.classList.add('hidden');return}const q=query.toLowerCase(),matches=allPatients.filter(p=>(p.first_name||'').toLowerCase().includes(q)||(p.last_name||'').toLowerCase().includes(q)||(p.email||'').toLowerCase().includes(q));if(!matches.length){dd.classList.add('hidden');return}dd.innerHTML=matches.map(p=>`<div class="combobox-item" data-id="${esc(p.id)}">${esc(p.first_name||'')} ${esc(p.last_name||'')} (${esc(p.email||'')})</div>`).join('');dd.classList.remove('hidden');dd.querySelectorAll('.combobox-item').forEach(e=>e.onmousedown=x=>{x.preventDefault();const p=allPatients.find(y=>y.id===e.dataset.id);if(p)onSelect(p)});}
document.addEventListener('click',e=>{if(!e.target.closest('.combobox-wrapper'))document.querySelectorAll('.combobox-dropdown').forEach(d=>d.classList.add('hidden'));});
function selectAptPatient(p){selectedAptPatient=p;document.getElementById('apt-patient-search').value=`${p.first_name||''} ${p.last_name||''}`;document.getElementById('apt-patient-dropdown').classList.add('hidden');document.getElementById('apt-patient-data').classList.remove('hidden');document.getElementById('apt-email').value=p.email||'';document.getElementById('apt-phone').value=p.phone||'';document.getElementById('apt-name').value=`${p.first_name||''} ${p.last_name||''}`.trim();document.getElementById('apt-dob').value=p.dob||'';document.getElementById('apt-age-display').textContent=(calcAge(p.dob)??'')!==''?`Wiek: ${calcAge(p.dob)} lat`:'';}
function selectAccountPatient(p){selectedAccountPatient=p;document.getElementById('account-search').value=`${p.first_name||''} ${p.last_name||''}`;document.getElementById('account-detail').classList.remove('hidden');document.getElementById('account-detail-title').textContent=`${p.first_name||''} ${p.last_name||''}`;document.getElementById('acc-email').value=p.email||'';document.getElementById('acc-email').setAttribute('readonly','');document.getElementById('acc-phone').value=p.phone||'';document.getElementById('acc-first').value=p.first_name||'';document.getElementById('acc-last').value=p.last_name||'';document.getElementById('acc-dob').value=p.dob||'';document.getElementById('acc-public-notes').value=p.public_notes||'';document.getElementById('acc-private-notes').value=p.private_notes||'';calcAgeField('acc-dob','acc-age');}
function openNewProfileInAccounts(){selectedAccountPatient=null;document.getElementById('account-search').value='';document.getElementById('account-detail').classList.remove('hidden');document.getElementById('account-detail-title').textContent='Nowy profil pacjenta';document.getElementById('acc-email').removeAttribute('readonly');['acc-email','acc-phone','acc-first','acc-last','acc-dob','acc-age','acc-public-notes','acc-private-notes'].forEach(id=>document.getElementById(id).value='');}
async function saveAccountPatient(e){e.preventDefault();if(!isTherapist){showToast('Brak uprawnień.','error');return}try{const email=document.getElementById('acc-email').value.trim(),phone=document.getElementById('acc-phone').value.trim(),first=document.getElementById('acc-first').value.trim(),last=document.getElementById('acc-last').value.trim(),dob=document.getElementById('acc-dob').value||null,public_notes=document.getElementById('acc-public-notes').value,private_notes=document.getElementById('acc-private-notes').value;if(!email){showToast('Podaj e-mail pacjenta','error');return}if(selectedAccountPatient){const r=await dbUpdate('profiles',{phone,first_name:first,last_name:last,dob,public_notes,private_notes},{id:selectedAccountPatient.id});}else{const existing=await sb.from('profiles').select('id').eq('email',email).maybeSingle();if(existing.error)throw existing.error;if(existing.data){showToast('Profil z tym adresem już istnieje.','error');return}const r=await sb.from('profiles').insert({email,phone,first_name:first,last_name:last,dob,public_notes,private_notes,role:'patient'});if(r.error)throw r.error}await loadPatients();showToast(selectedAccountPatient?'Dane pacjenta zaktualizowane':'Profil pacjenta zapisany');}catch(e){showToast('Błąd zapisu: '+e.message,'error')}}

function loadProfile(){if(!currentProfile)return;const p=currentProfile;document.getElementById('prof-email').value=p.email||'';document.getElementById('prof-phone').value=p.phone||'';document.getElementById('prof-first').value=p.first_name||'';document.getElementById('prof-last').value=p.last_name||'';document.getElementById('prof-dob').value=p.dob||'';document.getElementById('prof-notes').value=p.public_notes||'';calcAgeField('prof-dob','prof-age');if(!isTherapist&&p.profile_locked){document.getElementById('profile-locked-msg').classList.remove('hidden');['prof-phone','prof-first','prof-last','prof-dob'].forEach(id=>document.getElementById(id).disabled=true);document.getElementById('prof-save-btn').classList.add('hidden');}else{document.getElementById('profile-locked-msg').classList.add('hidden');}}
async function saveProfile(e){e.preventDefault();if(!currentProfile)return;if(!isTherapist&&currentProfile.profile_locked){showToast('Profil zablokowany – tylko terapeuta może zmienić dane','error');return}try{const updates={phone:document.getElementById('prof-phone').value.trim(),first_name:document.getElementById('prof-first').value.trim(),last_name:document.getElementById('prof-last').value.trim(),dob:document.getElementById('prof-dob').value||null,public_notes:document.getElementById('prof-notes').value};if(!isTherapist)updates.profile_locked=true;const r=await dbUpdate('profiles',updates,{id:currentUser.id});const p=await sb.from('profiles').select('*').eq('id',currentUser.id).single();if(p.error)throw p.error;currentProfile=p.data;loadProfile();if(!isTherapist&&updates.profile_locked)openModal('profile-save-popup');else showToast('Profil zapisany');}catch(e){showToast('Błąd zapisu: '+e.message,'error')}}
function calcAge(dob){if(!dob)return null;const [y,m,d]=dob.split('-').map(Number),now=new Date();let age=now.getFullYear()-y;if(now.getMonth()+1<m||(now.getMonth()+1===m&&now.getDate()<d))age--;return age>=0?age:null;}
function calcAgeField(dobId,ageId){const a=calcAge(document.getElementById(dobId).value);document.getElementById(ageId).value=a===null?'':`${a} lat`;}

async function loadNotifications(){if(!currentUser)return;let q=sb.from('notifications').select('*').order('created_at',{ascending:false});q=isTherapist?q.in('patient_email',THERAPIST_EMAILS):q.eq('patient_email',currentUser.email);const r=await q;if(r.error){console.error(r.error);return}allNotifications=r.data||[];updateNotifBadge();renderNotifications();}
function updateNotifBadge(){const b=document.getElementById('notif-badge'),n=allNotifications.filter(x=>!x.is_read).length;if(!b)return;b.textContent=n>99?'99+':String(n);b.classList.toggle('hidden',n===0);}
function parseNotificationType(type){if(!type)return null;const [action,...rest]=type.split(':');return{action,aptId:rest.join(':')||null};}
function isRescheduleForMe(action){return isTherapist?false:action==='reschedule_patient'||isTherapist&&action==='reschedule_therapist';}
function renderNotifications(){const list=document.getElementById('notifications-list');if(!list)return;let rows=allNotifications;if(notifFilter==='unread')rows=rows.filter(n=>!n.is_read);else if(notifFilter==='read')rows=rows.filter(n=>n.is_read);if(!rows.length){list.innerHTML=`<p class="empty-msg">${notifFilter==='unread'?'Brak nieprzeczytanych powiadomień':notifFilter==='read'?'Brak przeczytanych powiadomień':'Brak powiadomień'}</p>`;return}list.innerHTML=rows.map(n=>{const p=parseNotificationType(n.type),rel=p&&isRescheduleForMe(p.action),actions=rel&&!n.is_read?`<div class="notif-actions" onclick="event.stopPropagation()"><button class="btn btn-primary btn-sm" onclick="acceptRescheduleFromNotif('${esc(n.id)}','${esc(p.aptId)}')">Akceptuj termin</button><button class="btn btn-outline btn-sm" onclick="proposeAlternativeDateFromNotif('${esc(p.aptId)}','${p.action==='reschedule_therapist'?'therapist':'patient'}','${esc(n.id)}')">Zaproponuj inny termin</button></div>`:'';const icon=p&&(p.action==='reschedule_therapist'||p.action==='reschedule_patient')?'🔄':n.type?.startsWith('accepted_')?'✅':n.type==='cancel'?'❌':n.type==='broadcast'?'📢':n.type==='info'?'ℹ️':'🔔';return`<div class="card notif-card ${n.is_read?'read':''}" onclick="markNotifRead('${esc(n.id)}')"><div class="card-header"><h3>${n.is_read?'':'<span class="unread-dot"></span>'}${icon} ${renderNotifMessage(n.message)}</h3></div><span class="card-date">${esc(new Intl.DateTimeFormat('pl-PL',{timeZone:TZ,dateStyle:'short',timeStyle:'short'}).format(new Date(n.created_at)))}</span>${actions}</div>`}).join('');}
function filterNotifications(filter,btn){notifFilter=filter;document.querySelectorAll('#notif-sub-tabs .sub-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderNotifications();}
async function markNotifRead(id){const n=allNotifications.find(x=>x.id===id);if(!n||n.is_read)return;const r=await dbUpdate('notifications',{is_read:true},{id});n.is_read=true;updateNotifBadge();renderNotifications();}
async function markAllRead(){try{let q=sb.from('notifications').update({is_read:true});q=isTherapist?q.in('patient_email',THERAPIST_EMAILS):q.eq('patient_email',currentUser.email);const r=await q;if(r.error)throw r.error;allNotifications.forEach(n=>n.is_read=true);updateNotifBadge();renderNotifications();}catch(e){showToast('Błąd oznaczania powiadomień: '+e.message,'error')}}
async function sendBroadcast(){if(!isTherapist){showToast('Brak uprawnień.','error');return}const msg=document.getElementById('broadcast-msg').value.trim();if(!msg){showToast('Wpisz treść wiadomości','error');return}try{const r=await sb.from('profiles').select('email').eq('role','patient');if(r.error)throw r.error;if(!r.data?.length){showToast('Brak pacjentów','error');return}const ins=await sb.from('notifications').insert(r.data.map(p=>({patient_email:p.email,message:msg,type:'broadcast',is_read:false})));if(ins.error)throw ins.error;document.getElementById('broadcast-msg').value='';closeModalAll();showToast(`Wiadomość wysłana do ${r.data.length} pacjentów`);}catch(e){showToast('Błąd wysyłania: '+e.message,'error')}}
async function acceptRescheduleFromNotif(aptId,notifId){await acceptReschedule(aptId,notifId)}
function proposeAlternativeDateFromNotif(aptId,role,notifId){proposeAlternativeDate(aptId,role,notifId)}

async function loadExercises(){const r=await sb.from('exercises').select('*').order('title');if(r.error){showToast('Błąd ćwiczeń: '+r.error.message,'error');return}allExercises=r.data||[];const f=await sb.from('favorite_exercises').select('exercise_id').eq('user_id',currentUser.id);if(f.error){console.error(f.error);exerciseFavIds=[]}else exerciseFavIds=(f.data||[]).map(x=>x.exercise_id);renderExercises();}
function renderExercises(){const list=document.getElementById('exercises-list'),fav=document.querySelector('#exercise-sub-tabs .active')?.dataset.filter==='favorites',rows=fav?allExercises.filter(x=>exerciseFavIds.includes(x.id)):allExercises;if(!rows.length){list.innerHTML='<p class="empty-msg">Brak ćwiczeń</p>'}else list.innerHTML=rows.map(ex=>`<div class="card exercise-card"><div class="card-header"><h3><img src="icon.png" class="inline-icon" alt=""> ${esc(ex.title)}</h3></div><p class="card-desc">${esc(ex.description||'')}</p>${ex.link?`<a href="${esc(ex.link)}" target="_blank" rel="noopener" class="exercise-link">Pobierz materiały</a>`:'<span class="exercise-no-link">Ćwiczenie bez materiałów</span>'}<div class="card-months">${(ex.months||[]).map(m=>MONTH_LABELS[m-1]||'').join(', ')}</div><div class="card-actions"><button class="btn btn-outline btn-sm" onclick="toggleFavorite('${esc(ex.id)}',${exerciseFavIds.includes(ex.id)})">${exerciseFavIds.includes(ex.id)?'Ulubione':'Dodaj do ulubionych'}</button>${isTherapist?`<button class="btn btn-danger btn-sm" onclick="deleteExercise('${esc(ex.id)}')">Usuń</button>`:''}</div></div>`).join('');const side=document.getElementById('favorite-exercises-sidebar');side.classList.toggle('hidden',!exerciseFavIds.length);document.getElementById('favorites-list').innerHTML=allExercises.filter(x=>exerciseFavIds.includes(x.id)).map(x=>`<div class="fav-item">${esc(x.title)}</div>`).join('');}
function filterExercises(filter,btn){document.querySelectorAll('#exercise-sub-tabs .sub-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderExercises();}
async function toggleFavorite(id,current){try{const r=current?await sb.from('favorite_exercises').delete().eq('exercise_id',id).eq('user_id',currentUser.id):await sb.from('favorite_exercises').insert({exercise_id:id,user_id:currentUser.id});if(r.error)throw r.error;await loadExercises()}catch(e){showToast('Błąd ulubionych: '+e.message,'error')}}
async function deleteExercise(id){if(!isTherapist||!confirm('Usunąć ćwiczenie?'))return;try{const r=await sb.from('exercises').delete().eq('id',id);if(r.error)throw r.error;await loadExercises();showToast('Ćwiczenie usunięte')}catch(e){showToast('Błąd usuwania: '+e.message,'error')}}
async function saveExercise(e){e.preventDefault();if(!isTherapist){showToast('Brak uprawnień.','error');return}try{const r=await sb.from('exercises').insert({title:document.getElementById('ex-title').value.trim(),description:document.getElementById('ex-desc').value,link:document.getElementById('ex-link').value.trim()});if(r.error)throw r.error;closeModalAll();await loadExercises();showToast('Ćwiczenie dodane')}catch(e){showToast('Błąd dodawania: '+e.message,'error')}}

function openModal(id){document.getElementById(id)?.classList.remove('hidden');document.body.style.overflow='hidden'}
function closeModalAll(){document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'));document.body.style.overflow=''}
function showToast(msg,type='success'){const c=document.getElementById('toast-container');if(!c)return;const t=document.createElement('div');t.className=`toast toast-${type}`;t.textContent=msg;c.appendChild(t);setTimeout(()=>t.remove(),3500)}
function renderNotifMessage(msg){let s=esc(msg);s=s.replace(/\{\{black:(.*?)\}\}/g,'<span style="color:#1e293b;font-weight:600">$1</span>').replace(/\{\{green:(.*?)\}\}/g,'<span style="color:#22c55e;font-weight:600">$1</span>');return s}
function esc(s){const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML}
async function logout(){await sb.auth.signOut();localStorage.removeItem('sb-session');location.href='login.html'}