/* Europe/Warsaw + recurring appointment fixes. */
(function(){
'use strict';
const TZ='Europe/Warsaw';
const pad=n=>String(n).padStart(2,'0');
function warsawLocalToISO(date,time){
 const [y,m,d]=date.split('-').map(Number),[h,min]=time.split(':').map(Number);
 const base=Date.UTC(y,m-1,d,h,min,0), fmt=new Intl.DateTimeFormat('en-GB',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23');
 for(let off=-14;off<=14;off++){
  const x=new Date(base-off*3600000),p=Object.fromEntries(fmt.formatToParts(x).filter(a=>a.type!=='literal').map(a=>[a.type,Number(a.value)]));
  if(p.year===y&&p.month===m&&p.day===d&&p.hour===h&&p.minute===min&&p.second===0)return x.toISOString();
 }
 throw new Error('Nie udało się przeliczyć daty dla Europe/Warsaw.');
}
function warsawTime(v){const d=new Date(v);return new Intl.DateTimeFormat('pl-PL',{timeZone:TZ,hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d)}
function warsawDateTime(v){const d=new Date(v);return new Intl.DateTimeFormat('pl-PL',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(d)}
window.polandDateTimeToISO=warsawLocalToISO;
window.generateRecurringAppointments=function(startDate,startTime,type,months){
 const [y,m,d]=startDate.split('-').map(Number), selected=new Set((months||[]).map(Number)),out=[];
 if(!selected.size)return out;
 if(type==='monthly'){
  for(const mo of [...selected].sort((a,b)=>a-b)){
   const last=new Date(Date.UTC(y,mo,0)).getUTCDate(),day=Math.min(d,last),date=`${y}-${pad(mo)}-${pad(day)}`;
   if(new Date(warsawLocalToISO(date,startTime))>new Date(warsawLocalToISO(startDate,startTime)))out.push({date,time:startTime});
  }
  return out;
 }
 const step=type==='biweekly'?14:7,cursor=new Date(Date.UTC(y,m-1,d)),end=new Date(Date.UTC(y,11,31));
 while(true){cursor.setUTCDate(cursor.getUTCDate()+step);if(cursor>end)break;const cm=cursor.getUTCMonth()+1;if(selected.has(cm))out.push({date:`${cursor.getUTCFullYear()}-${pad(cm)}-${pad(cursor.getUTCDate())}`,time:startTime})}
 return out;
};
async function slotTaken(date,time,excludeId){let q=sb.from('appointments').select('id').eq('appointment_date',warsawLocalToISO(date,time)).neq('status','cancelled').limit(1);if(excludeId)q=q.neq('id',excludeId);const{data,error}=await q;if(error)throw error;return !!data?.length}
window.initCalendar=function(){const el=document.getElementById('calendar');if(!el)return;if(calendar?.destroy)calendar.destroy();calendar=new FullCalendar.Calendar(el,{locale:'pl',initialView:'dayGridMonth',headerToolbar:{left:'dayGridMonth,timeGridWeek,timeGridDay',center:'title',right:'prev,today,next'},buttonText:{month:'Miesiąc',week:'Tydzień',day:'Dzień',today:'Dziś'},timeZone:'local',slotMinTime:'07:00:00',slotMaxTime:'21:00:00',slotDuration:'01:00:00',allDaySlot:false,height:'auto',displayEventTime:true,eventTimeFormat:{hour:'2-digit',minute:'2-digit',hour12:false},events:fetchCalendarEvents,eventClick:handleEventClick,dateClick:isTherapist?handleDateClick:undefined});calendar.render()};
window.initAptTimeSelect=function(){const s=document.getElementById('apt-time');if(!s)return;const old=s.value;s.innerHTML='';for(let h=7;h<=21;h++){const o=document.createElement('option');o.value=`${pad(h)}:00`;o.textContent=o.value;s.appendChild(o)}s.value=[...s.options].some(o=>o.value===old)?old:'09:00'};
window.openNewAptModal=function(dateStr){selectedAptPatient=null;document.getElementById('apt-patient-search').value='';document.getElementById('apt-patient-dropdown').classList.add('hidden');document.getElementById('apt-patient-data').classList.add('hidden');document.getElementById('apt-title').value='Wizyta logopedyczna';document.getElementById('apt-date').value=dateStr||'';document.getElementById('apt-recurring').checked=false;document.getElementById('recurring-options').classList.add('hidden');document.getElementById('apt-recurring-type').value='weekly';initAptTimeSelect();document.getElementById('apt-time').value='09:00';document.querySelectorAll('#recurring-months .month-btn').forEach(b=>b.classList.remove('selected'));openModal('new-appointment-modal')};
window.createAppointment=async function(e){e.preventDefault();if(!isTherapist){showToast('Tylko logopeda może tworzyć wizyty.','error');return}if(!selectedAptPatient){showToast('Wybierz pacjenta z listy','error');return}const date=document.getElementById('apt-date').value,time=document.getElementById('apt-time').value,title=document.getElementById('apt-title').value.trim(),rec=document.getElementById('apt-recurring').checked,type=rec?document.getElementById('apt-recurring-type').value:null,months=rec?getSelectedMonths('recurring-months'):[];if(!date||!time){showToast('Podaj datę i godzinę','error');return}if(rec&&!months.length){showToast('Wybierz co najmniej jeden miesiąc dla wizyt cyklicznych.','error');return}try{const iso=warsawLocalToISO(date,time);if(await slotTaken(date,time)){showToast('Ten termin jest już zajęty. Wybierz inną godzinę.','error');return}const patient={patient_email:selectedAptPatient.email,patient_name:`${selectedAptPatient.first_name||''} ${selectedAptPatient.last_name||''}`.trim(),patient_phone:selectedAptPatient.phone||'',patient_dob:selectedAptPatient.dob||null};const r=await sb.from('appointments').insert({...patient,appointment_date:iso,title,status:'confirmed',recurring_type:type||'weekly'}).select().single();if(r.error)throw r.error;if(rec){const generated=generateRecurringAppointments(date,time,type,months),rows=[];for(const a of generated)if(!(await slotTaken(a.date,a.time)))rows.push({...patient,appointment_date:warsawLocalToISO(a.date,a.time),title,status:'pending',recurring_type:type,recurring_parent:r.data.id});if(rows.length){const ir=await sb.from('appointments').insert(rows);if(ir.error)throw ir.error}}calendar?.refetchEvents();closeModalAll();showToast('Wizyta utworzona')}catch(err){console.error(err);showToast('Błąd tworzenia wizyty: '+err.message,'error')}};
window.loadReschedSlots=async function(aptId){const date=document.getElementById('resched-date').value,grid=document.getElementById('resched-slots');if(!date||!grid)return;try{const start=warsawLocalToISO(date,'00:00'),end=warsawLocalToISO(date,'23:59'),r=await sb.from('appointments').select('id,appointment_date').gte('appointment_date',start).lte('appointment_date',end).neq('status','cancelled').neq('id',aptId);if(r.error)throw r.error;const taken=new Set((r.data||[]).map(a=>warsawTime(a.appointment_date)));grid.innerHTML='';for(let h=7;h<=21;h++){const t=`${pad(h)}:00`,busy=taken.has(t),b=document.createElement('button');b.type='button';b.className='slot-btn'+(busy?' taken':'');b.textContent=busy?`${t} — Zajęte`:`${t} — Dostępne`;b.disabled=busy;if(!busy)b.onclick=()=>{grid.querySelectorAll('.slot-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const c=document.getElementById('resched-confirm');c.disabled=false;c.dataset.time=t};grid.appendChild(b)}}catch(err){console.error(err);grid.innerHTML='<div class="empty-msg">Nie udało się sprawdzić dostępności.</div>'}};
function rootId(a){return a.recurring_parent||a.id}
function seriesPopup(apt){const old=document.getElementById('series-cancel-popup');if(old)old.remove();const m=document.createElement('div');m.id='series-cancel-popup';m.className='modal';m.style.display='flex';const c=document.createElement('div');c.className='modal-content';c.style.maxWidth='520px';c.innerHTML='<h3>Wizyta cykliczna</h3><p>Ta wizyta należy do <strong>serii cyklicznej</strong>.<br>Co chcesz zrobić?</p>';const f=document.createElement('div');f.className='modal-footer';const one=document.createElement('button');one.className='btn btn-outline btn-sm';one.textContent='Odwołaj tylko tę wizytę';const all=document.createElement('button');all.className='btn btn-danger btn-sm';all.textContent='Odwołaj całą serię';const back=document.createElement('button');back.className='btn btn-outline btn-sm';back.textContent='Wróć';f.append(one,all,back);c.appendChild(f);m.appendChild(c);document.body.appendChild(m);one.onclick=()=>{m.remove();cancelOne(apt.id)};all.onclick=()=>{m.remove();cancelSeries(apt)};back.onclick=()=>m.remove()}
async function notifyCancel(a,all=false){if(isTherapist&&a.patient_email)await sb.from('notifications').insert({patient_email:a.patient_email,message:all?'Cała seria cyklicznych wizyt została odwołana przez logopedę.':'Wizyta została odwołana przez logopedę.',type:'cancel',is_read:false});else if(!isTherapist)await sb.from('notifications').insert({patient_email:THERAPIST_EMAILS[0],message:all?`Pacjent ${a.patient_name||''} odwołał całą serię wizyt.`:`Pacjent ${a.patient_name||''} odwołał wizytę.`,type:'cancel',is_read:false})}
async function cancelOne(id){if(!confirm('Na pewno odwołać tę wizytę?'))return;const r=await sb.from('appointments').select('id,patient_email,patient_name,title').eq('id',id).single();if(r.error){showToast('Nie udało się pobrać wizyty: '+r.error.message,'error');return}const u=await sb.from('appointments').update({status:'cancelled',title:stripRescheduleRequest(r.data.title||'')}).eq('id',id);if(u.error){showToast('Nie udało się odwołać wizyty: '+u.error.message,'error');return}await notifyCancel(r.data);calendar?.refetchEvents();loadNotifications();closeModalAll();showToast('Wizyta anulowana')}
async function cancelSeries(apt){if(!confirm('Na pewno odwołać WSZYSTKIE wizyty z tej serii? Tej operacji nie można cofnąć.'))return;const r=await sb.from('appointments').select('id').or(`id.eq.${rootId(apt)},recurring_parent.eq.${rootId(apt)}`);if(r.error){showToast('Nie udało się pobrać serii: '+r.error.message,'error');return}const ids=(r.data||[]).map(a=>a.id);if(!ids.length){showToast('Nie znaleziono powiązanych wizyt.','error');return}const u=await sb.from('appointments').update({status:'cancelled'}).in('id',ids);if(u.error){showToast('Nie udało się anulować serii: '+u.error.message,'error');return}await notifyCancel(apt,true);calendar?.refetchEvents();loadNotifications();closeModalAll();showToast(`Anulowano ${ids.length} wizyt z serii.`)}
window.cancelAppointment=async function(id){const r=await sb.from('appointments').select('id,recurring_parent,patient_email,patient_name,title,appointment_date').eq('id',id).single();if(r.error||!r.data){showToast('Nie udało się znaleźć wizyty.','error');return}const ch=await sb.from('appointments').select('id').eq('recurring_parent',id).limit(1);if(r.data.recurring_parent||(ch.data&&ch.data.length)){seriesPopup(r.data);return}cancelOne(id)};
window.showAptDetail=function(a){const age=calcAge(a.patient_dob||''),ageStr=age!==null?` (${age} lat)`:'';const dt=warsawDateTime(a.appointment_date),i=dt.lastIndexOf(',');const ds=i>=0?dt.slice(0,i):dt,ts=i>=0?dt.slice(i+1).trim():'';const b=document.getElementById('modal-body');b.innerHTML=`<div class="detail-row"><strong>Pacjent:</strong> ${esc(a.patient_name||'')}${ageStr}</div><div class="detail-row"><strong>Data:</strong> ${esc(ds)}</div><div class="detail-row"><strong>Godzina:</strong> ${esc(ts)}</div><div class="detail-row"><strong>Status:</strong> ${statusLabel(a.status)}</div>${a.patient_email?`<div class="detail-row"><strong>E-mail:</strong> ${esc(a.patient_email)}</div>`:''}${a.patient_phone?`<div class="detail-row"><strong>Telefon:</strong> ${esc(a.patient_phone)}</div>`:''}${a.recurring_type?`<div class="detail-row"><strong>Cykliczność:</strong> ${recurringLabel(a.recurring_type)}</div>`:''}`;const ac=document.getElementById('modal-actions');ac.innerHTML='';if(a.status!=='cancelled')ac.innerHTML+=`<button class="btn btn-danger btn-sm" onclick="cancelAppointment('${a.id}')">Odwołaj wizytę</button> `;if(a.status==='reschedule_requested'&&isTherapist){ac.innerHTML+=`<button class="btn btn-primary btn-sm" onclick="acceptReschedule('${a.id}')">Akceptuj proponowany termin</button> `;ac.innerHTML+=`<button class="btn btn-outline btn-sm" onclick="proposeAlternativeDate('${a.id}','therapist')">Zaproponuj inny termin</button> `}else if(a.status==='reschedule_proposed'&&!isTherapist){ac.innerHTML+=`<button class="btn btn-primary btn-sm" onclick="acceptReschedule('${a.id}')">Akceptuj proponowany termin</button> `;ac.innerHTML+=`<button class="btn btn-outline btn-sm" onclick="proposeAlternativeDate('${a.id}','patient')">Zaproponuj inny termin</button> `}else if(isTherapist&&a.status!=='cancelled')ac.innerHTML+=`<button class="btn btn-outline btn-sm" onclick="openReschedule('${a.id}')">Przełóż wizytę</button> `;else if(!isTherapist&&a.status!=='cancelled'&&a.status!=='reschedule_requested'&&a.status!=='reschedule_proposed')ac.innerHTML+=`<button class="btn btn-outline btn-sm" onclick="requestReschedule('${a.id}')">Poproś o przełożenie</button> `;ac.innerHTML+=`<button class="btn btn-outline btn-sm" onclick="closeModalAll()">Wróć</button>`;document.getElementById('modal-title').textContent=stripRescheduleRequest(a.title||'')||'Szczegóły wizyty';openModal('appointment-modal')};
window.acceptReschedule=async function(id,notifId){const r=await sb.from('appointments').select('id,title,patient_email,patient_name,appointment_date').eq('id',id).single();if(r.error||!r.data){showToast('Wizyta nie istnieje','error');return}const a=r.data,info=extractRescheduleInfo(a);if(!info){showToast('Brak propozycji przełożenia','error');return}const[date,time]=info.proposedDate.split(' ');let iso;try{iso=warsawLocalToISO(date,time)}catch{showToast('Nieprawidłowa proponowana data.','error');return}const u=await sb.from('appointments').update({appointment_date:iso,status:'confirmed',title:stripRescheduleRequest(a.title||'')}).eq('id',id);if(u.error){showToast('Błąd: '+u.error.message,'error');return}await sb.from('notifications').insert({patient_email:info.role==='patient'?a.patient_email:THERAPIST_EMAILS[0],message:info.role==='patient'?`Logopeda zaakceptował Twój proponowany termin: ${info.proposedDate}. Wizyta potwierdzona!`:`Pacjent ${a.patient_name||''} zaakceptował proponowany termin: ${info.proposedDate}`,type:info.role==='patient'?'accepted_patient':'accepted_therapist',is_read:false});calendar?.refetchEvents();loadNotifications();closeModalAll();showToast('Termin potwierdzony: '+info.proposedDate)};
function replaceReschedButton(){const old=document.getElementById('resched-confirm');if(!old)return;const b=old.cloneNode(true);old.replaceWith(b);b.addEventListener('click',async function(){const id=this.dataset.aptId,mode=this.dataset.mode||'therapist',date=document.getElementById('resched-date').value,time=this.dataset.time;if(!date||!time)return;try{const iso=warsawLocalToISO(date,time),str=`${date} ${time}`,r=await sb.from('appointments').select('id,title,patient_email,patient_name,appointment_date').eq('id',id).single();if(r.error||!r.data){showToast('Wizyta nie istnieje','error');return}const a=r.data,base=stripRescheduleRequest(a.title||''),orig=warsawDateTime(a.appointment_date);let u;if(mode==='patient'||mode==='patient_counter')u=await sb.from('appointments').update({status:'reschedule_requested',title:`${base} [Prośba o przełożenie na ${str}]`}).eq('id',id);else if(mode==='therapist_counter')u=await sb.from('appointments').update({status:'reschedule_proposed',title:`${base} [Propozycja logopedy: ${str}]`}).eq('id',id);else u=await sb.from('appointments').update({appointment_date:iso,status:'confirmed',title:base}).eq('id',id);if(u.error)throw u.error;if(mode==='patient'||mode==='patient_counter')await sb.from('notifications').insert({patient_email:THERAPIST_EMAILS[0],message:`Pacjent ${a.patient_name||''} prosi o przełożenie wizyty z {{black:${orig}}} na {{green:${str}}}`,type:'reschedule_therapist:'+id,is_read:false});else if(mode==='therapist_counter')await sb.from('notifications').insert({patient_email:a.patient_email,message:`Logopeda proponuje nowy termin wizyty z {{black:${orig}}} na {{green:${str}}}`,type:'reschedule_patient:'+id,is_read:false});else await sb.from('notifications').insert({patient_email:a.patient_email,message:`Logopeda przełożył Twoją wizytę na ${str}`,type:'info',is_read:false});calendar?.refetchEvents();loadNotifications();closeModalAll();showToast(mode==='therapist'?`Wizyta przełożona na ${str}`:`Propozycja wysłana: ${str}`)}catch(e){console.error(e);showToast('Błąd: '+e.message,'error')}})}
function replaceAppointmentForm(){const old=document.getElementById('new-appointment-form');if(!old)return;const f=old.cloneNode(true);old.replaceWith(f);f.addEventListener('submit',window.createAppointment)}
document.addEventListener('DOMContentLoaded',()=>{replaceReschedButton();replaceAppointmentForm()});
})();